name: calculadora-flutter
version: '1.0'
summary: Calculadora básica em flutter
description: Uma calculadora básica feita em flutter, porem muito bonita.

confinement: strict
base: core18

parts:
  calculadora:
    plugin: flutter
    source: https://github.com/Marcel0Henrique/calculadora_flutter
    flutter-target: lib/main.dart

apps:
  calculadora:
    command: calculadora-flutter
    extensions: [flutter-dev]
